#!/usr/bin/env python3
"""Add new odds and time tools"""
import json

with open('tools_database.json', 'r', encoding='utf-8') as f:
    db = json.load(f)

# Add tid category if not exists
if 'tid' not in db['categories']:
    db['categories']['tid'] = {"name": "Tid og Dato", "icon": "📅"}

new_tools = [
    # ODDS tools
    {"slug":"texas-holdem-kalkulator","title":"Texas Hold'em Kalkulator","category":"odds","description":"Beregn Texas Hold'em poker odds","formula":"texas_holdem","keywords":"texas holdem kalkulator poker odds","inputs":[{"id":"hole_cards","label":"Dine kort (f.eks AS KH)","type":"text","placeholder":"AS KH"},{"id":"outs","label":"Antall outs","type":"number","placeholder":"8"},{"id":"street","label":"Runde","type":"select","options":["Flop (2 kort igjen)","Turn (1 kort igjen)"]}]},
    {"slug":"baccarat-kalkulator","title":"Baccarat Kalkulator","category":"odds","description":"Beregn baccarat odds og husfordel","formula":"baccarat_calc","keywords":"baccarat kalkulator odds husfordel","inputs":[{"id":"bet_type","label":"Innsatstype","type":"select","options":["Spiller","Banker","Uavgjort"]},{"id":"stake","label":"Innsats (kr)","type":"number","placeholder":"100"}]},
    {"slug":"risiko-for-ruin-kalkulator","title":"Risiko for Ruin Kalkulator","category":"odds","description":"Beregn risiko for å miste hele bankroll","formula":"risk_of_ruin","keywords":"risiko ruin kalkulator bankroll management","inputs":[{"id":"win_rate","label":"Vinnerate (%)","type":"number","placeholder":"55"},{"id":"bankroll","label":"Bankroll (kr)","type":"number","placeholder":"10000"},{"id":"bet_size","label":"Innsats per runde (kr)","type":"number","placeholder":"100"}]},
    {"slug":"implisert-sannsynlighet-kalkulator","title":"Implisert Sannsynlighetskalkulator","category":"odds","description":"Konverter odds til implisert sannsynlighet","formula":"implied_probability","keywords":"implisert sannsynlighet kalkulator odds","inputs":[{"id":"odds_type","label":"Odds format","type":"select","options":["Desimal","Amerikansk","Fraksjon"]},{"id":"odds_value","label":"Odds verdi","type":"text","placeholder":"2.50"}]},
    {"slug":"omaha-poker-kalkulator","title":"Omaha Poker Kalkulator","category":"odds","description":"Beregn Omaha poker odds og equity","formula":"omaha_poker","keywords":"omaha poker kalkulator odds equity","inputs":[{"id":"outs","label":"Antall outs","type":"number","placeholder":"12"},{"id":"street","label":"Runde","type":"select","options":["Flop","Turn"]},{"id":"pot","label":"Pott (kr)","type":"number","placeholder":"500"},{"id":"call","label":"Call beløp (kr)","type":"number","placeholder":"100"}]},
    {"slug":"bingo-odds-kalkulator","title":"Bingo Odds Kalkulator","category":"odds","description":"Beregn bingo odds og sannsynlighet","formula":"bingo_odds","keywords":"bingo odds kalkulator sannsynlighet","inputs":[{"id":"cards","label":"Antall bingokort","type":"number","placeholder":"3"},{"id":"players","label":"Antall spillere","type":"number","placeholder":"50"},{"id":"calls","label":"Antall tall trukket","type":"number","placeholder":"30"}]},
    {"slug":"blackjack-husfordel-kalkulator","title":"Blackjack Husfordel Kalkulator","category":"odds","description":"Beregn blackjack husfordel basert på regler","formula":"blackjack_house_edge","keywords":"blackjack husfordel kalkulator regler","inputs":[{"id":"decks","label":"Antall kortstokker","type":"select","options":["1","2","4","6","8"]},{"id":"soft17","label":"Dealer på soft 17","type":"select","options":["Stå","Trekk"]},{"id":"double","label":"Dobling tillatt","type":"select","options":["Alle kort","9-11 kun","10-11 kun"]}]},
    {"slug":"sports-futures-kalkulator","title":"Sports Futures Kalkulator","category":"odds","description":"Beregn futures betting utbetaling","formula":"sports_futures","keywords":"sports futures kalkulator odds utbetaling","inputs":[{"id":"stake","label":"Innsats (kr)","type":"number","placeholder":"500"},{"id":"odds","label":"Futures odds","type":"number","placeholder":"8.5"},{"id":"probability","label":"Din estimerte sannsynlighet (%)","type":"number","placeholder":"15"}]},
    {"slug":"roulette-bet-kalkulator","title":"Roulette Bet Kalkulator","category":"odds","description":"Beregn roulette innsatser og utbetalinger","formula":"roulette_bet","keywords":"roulette bet kalkulator innsats utbetaling","inputs":[{"id":"bet_amount","label":"Innsats (kr)","type":"number","placeholder":"100"},{"id":"bet_type","label":"Innsatstype","type":"select","options":["Enkelt tall (35:1)","Rød/Sort (1:1)","Odde/Jevn (1:1)","Dusin (2:1)","Kolonne (2:1)","Split (17:1)","Street (11:1)","Corner (8:1)","Line (5:1)"]},{"id":"sessions","label":"Antall runder","type":"number","placeholder":"10"}]},
    {"slug":"rett-spill-kalkulator","title":"Rett Spill Kalkulator","category":"odds","description":"Beregn rett spill kombinasjoner og odds","formula":"straight_bet","keywords":"rett spill kalkulator odds kombinasjoner","inputs":[{"id":"stake","label":"Innsats (kr)","type":"number","placeholder":"100"},{"id":"odds","label":"Desimalodds","type":"number","placeholder":"1.90"},{"id":"result","label":"Resultat","type":"select","options":["Vant","Tapte","Push"]}]},

    # TID (Time) tools
    {"slug":"sovnkalkulator","title":"Søvnkalkulator","category":"tid","description":"Beregn optimal søvntid og søvnsykluser","formula":"sleep_calc","keywords":"søvnkalkulator søvnsyklus leggetid","inputs":[{"id":"wakeup_time","label":"Oppvåkningstid","type":"time","placeholder":"07:00"},{"id":"cycles","label":"Antall søvnsykluser (anbefalt: 5-6)","type":"number","placeholder":"6"}]},
    {"slug":"oppetidskalkulator","title":"Oppetidskalkulator","category":"tid","description":"Beregn system oppetid og nedetid","formula":"uptime_calc","keywords":"oppetidskalkulator uptime nedetid server","inputs":[{"id":"uptime_percent","label":"Oppetid (%)","type":"number","placeholder":"99.9"},{"id":"period","label":"Tidsperiode","type":"select","options":["Per dag","Per uke","Per måned","Per år"]}]},
    {"slug":"arbeidsdagskalkulator","title":"Arbeidsdagskalkulator","category":"tid","description":"Beregn antall arbeidsdager mellom datoer","formula":"workdays_calc","keywords":"arbeidsdagskalkulator virkedager kalender","inputs":[{"id":"start_date","label":"Startdato","type":"date","placeholder":""},{"id":"end_date","label":"Sluttdato","type":"date","placeholder":""},{"id":"exclude_holidays","label":"Ekskluder helligdager","type":"select","options":["Ja","Nei"]}]},
    {"slug":"flytid-kalkulator","title":"Flytid Kalkulator","category":"tid","description":"Beregn flytid og tidssoneforskjell","formula":"flight_time","keywords":"flytid kalkulator tidssone reise","inputs":[{"id":"distance","label":"Avstand (km)","type":"number","placeholder":"1000"},{"id":"speed","label":"Hastighet (km/t)","type":"number","placeholder":"900"},{"id":"timezone_diff","label":"Tidssoneforskjell (timer)","type":"number","placeholder":"2"}]},
    {"slug":"frist-kalkulator","title":"Frist Kalkulator","category":"tid","description":"Beregn frister og tidsfrister","formula":"deadline_calc","keywords":"frist kalkulator tidsfrist deadline","inputs":[{"id":"start_date","label":"Startdato","type":"date","placeholder":""},{"id":"days","label":"Antall dager","type":"number","placeholder":"30"},{"id":"skip_weekends","label":"Hopp over helger","type":"select","options":["Ja","Nei"]}]},
    {"slug":"halv-bursdag-kalkulator","title":"Halv Bursdagskalkulator","category":"tid","description":"Finn din halve bursdag","formula":"half_birthday","keywords":"halv bursdag kalkulator dato","inputs":[{"id":"birthday","label":"Din bursdag","type":"date","placeholder":""}]},
    {"slug":"unix-tid-kalkulator","title":"Unix Tid Kalkulator","category":"tid","description":"Konverter Unix timestamp til dato og omvendt","formula":"unix_time","keywords":"unix tid kalkulator timestamp konverter","inputs":[{"id":"unix_timestamp","label":"Unix timestamp (sekunder)","type":"number","placeholder":"1700000000"}]},
    {"slug":"tidsvarighet-kalkulator","title":"Tidsvarighetskalkulator","category":"tid","description":"Beregn tidsvarighet mellom to tidspunkter","formula":"time_duration","keywords":"tidsvarighet kalkulator tid mellom","inputs":[{"id":"start_time","label":"Starttid","type":"time","placeholder":"09:00"},{"id":"end_time","label":"Sluttid","type":"time","placeholder":"17:30"},{"id":"break_minutes","label":"Pause (minutter)","type":"number","placeholder":"30"}]},
    {"slug":"kronologisk-alder-kalkulator","title":"Kronologisk Alderskalkulator","category":"tid","description":"Beregn nøyaktig kronologisk alder","formula":"chronological_age","keywords":"kronologisk alder kalkulator nøyaktig","inputs":[{"id":"birthdate","label":"Fødselsdato","type":"date","placeholder":""},{"id":"target_date","label":"Måldate (tom = i dag)","type":"date","placeholder":""}]},
    {"slug":"tidskalkulator","title":"Tidskalkulator","category":"tid","description":"Legg til eller trekk fra tid","formula":"time_calc","keywords":"tidskalkulator legg til tid trekk fra","inputs":[{"id":"start_time","label":"Starttid","type":"time","placeholder":"10:30"},{"id":"add_hours","label":"Legg til timer","type":"number","placeholder":"3"},{"id":"add_minutes","label":"Legg til minutter","type":"number","placeholder":"45"}]},
    {"slug":"minutter-til-desimal","title":"Minutter til Desimal Konverter","category":"tid","description":"Konverter minutter til desimaltimer","formula":"minutes_to_decimal","keywords":"minutter til desimal konverter timer","inputs":[{"id":"hours","label":"Timer","type":"number","placeholder":"2"},{"id":"minutes","label":"Minutter","type":"number","placeholder":"30"}]},
    {"slug":"forretningsdager-kalkulator","title":"Forretningsdager Kalkulator","category":"tid","description":"Legg til forretningsdager til en dato","formula":"business_days_calc","keywords":"forretningsdager kalkulator virkedager dato","inputs":[{"id":"start_date","label":"Startdato","type":"date","placeholder":""},{"id":"business_days","label":"Antall forretningsdager","type":"number","placeholder":"5"}]},
    {"slug":"ukedag-kalkulator","title":"Ukedagskalkulator","category":"tid","description":"Finn hvilken ukedag en dato er","formula":"weekday_calc","keywords":"ukedag kalkulator dato ukedag","inputs":[{"id":"date","label":"Dato","type":"date","placeholder":""}]},
    {"slug":"desimal-til-tid","title":"Desimal til Tid Kalkulator","category":"tid","description":"Konverter desimaltimer til timer og minutter","formula":"decimal_to_time","keywords":"desimal til tid kalkulator timer minutter","inputs":[{"id":"decimal_hours","label":"Desimaltimer","type":"number","placeholder":"2.75"}]},
    {"slug":"bursdagskalkulator","title":"Bursdagskalkulator","category":"tid","description":"Beregn alder og neste bursdag","formula":"birthday_calc","keywords":"bursdagskalkulator alder neste bursdag","inputs":[{"id":"birthday","label":"Fødselsdato","type":"date","placeholder":""}]},
    {"slug":"pluto-tid-kalkulator","title":"Pluto Tid Kalkulator","category":"tid","description":"Beregn din alder på Pluto","formula":"pluto_time","keywords":"pluto tid kalkulator planeter alder","inputs":[{"id":"age","label":"Din alder på Jorden (år)","type":"number","placeholder":"30"}]},
    {"slug":"timekalkulator","title":"Timekalkulator","category":"tid","description":"Beregn total arbeidstid og lønn","formula":"hour_calc","keywords":"timekalkulator arbeidstid lønn total","inputs":[{"id":"hours_per_day","label":"Timer per dag","type":"number","placeholder":"8"},{"id":"days","label":"Antall dager","type":"number","placeholder":"5"},{"id":"hourly_rate","label":"Timelønn (kr)","type":"number","placeholder":"250"}]},
    {"slug":"forloept-tid-kalkulator","title":"Kalkulator for Forløpt Tid","category":"tid","description":"Beregn forløpt tid siden en dato","formula":"elapsed_time","keywords":"forløpt tid kalkulator siden dato","inputs":[{"id":"past_date","label":"Tidligere dato","type":"date","placeholder":""},{"id":"past_time","label":"Tidligere tidspunkt","type":"time","placeholder":"00:00"}]},
    {"slug":"nedtellingstimer","title":"Nedtellingstimer","category":"tid","description":"Beregn tid til en fremtidig dato","formula":"countdown_timer","keywords":"nedtellingstimer kalkulator fremtidig dato","inputs":[{"id":"target_date","label":"Måldato","type":"date","placeholder":""},{"id":"target_time","label":"Måltidspunkt","type":"time","placeholder":"00:00"}]},
    {"slug":"tidsforskjell-kalkulator","title":"Tidsforskjell Kalkulator","category":"tid","description":"Beregn tidsforskjell mellom to tidspunkter","formula":"time_difference","keywords":"tidsforskjell kalkulator mellom tidspunkter","inputs":[{"id":"time1","label":"Tidspunkt 1","type":"time","placeholder":"09:00"},{"id":"time2","label":"Tidspunkt 2","type":"time","placeholder":"17:30"}]},
    {"slug":"dagteller","title":"Dagteller","category":"tid","description":"Tell dager mellom to datoer","formula":"day_counter","keywords":"dagteller kalkulator dager mellom datoer","inputs":[{"id":"date1","label":"Dato 1","type":"date","placeholder":""},{"id":"date2","label":"Dato 2","type":"date","placeholder":""}]},
    {"slug":"sovnsyklus-kalkulator","title":"Søvnsyklus Kalkulator","category":"tid","description":"Beregn søvnsykluser og optimal oppvåkning","formula":"sleep_cycle","keywords":"søvnsyklus kalkulator optimal oppvåkning","inputs":[{"id":"sleep_time","label":"Leggetid","type":"time","placeholder":"23:00"},{"id":"cycle_length","label":"Sykluslengde (minutter)","type":"number","placeholder":"90"}]},
    {"slug":"desimal-til-minutter","title":"Desimal til Minutter Konverterer","category":"tid","description":"Konverter desimaltimer til minutter","formula":"decimal_to_minutes","keywords":"desimal til minutter konverterer timer","inputs":[{"id":"decimal","label":"Desimaltimer","type":"number","placeholder":"1.5"}]},
    {"slug":"minutter-til-timer-minutter","title":"Minutter til Timer og Minutter Konverter","category":"tid","description":"Konverter minutter til timer og minutter","formula":"min_to_hrs_mins","keywords":"minutter til timer minutter konverter","inputs":[{"id":"total_minutes","label":"Totalt antall minutter","type":"number","placeholder":"150"}]}
]

existing_slugs = [t['slug'] for t in db['tools']]
added = 0
for tool in new_tools:
    if tool['slug'] not in existing_slugs:
        db['tools'].append(tool)
        added += 1
        print(f"  Added: {tool['slug']}")
    else:
        print(f"  Skipped: {tool['slug']}")

with open('tools_database.json', 'w', encoding='utf-8') as f:
    json.dump(db, f, ensure_ascii=False, indent=2)

print(f"\nDone! Added {added} tools. Total: {len(db['tools'])}")
