import json

with open('tools_database.json', encoding='utf-8') as f:
    db = json.load(f)

with open('../assets/js/calc.js', encoding='utf-8') as f:
    js = f.read()

# Map of wrong formula -> correct formula
fixes = {
    'bmi_advanced': 'bmi',
    'calories_advanced': 'calories',
    'idealweight_advanced': 'idealweight',
    'bmr_advanced': 'bmr',
    'tdee_advanced': 'tdee',
    'weightloss_advanced': 'weightloss',
    'water_advanced': 'water',
    'heartrate_advanced': 'heartrate',
    'protein_advanced': 'protein',
    'pregnancy_advanced': 'pregnancy',
    'bloodpressure_advanced': 'bloodpressure',
    'sleep_advanced': 'sleep',
    'loan_advanced': 'loan',
    'interest_advanced': 'interest',
    'savings_advanced': 'savings',
    'vat_advanced': 'vat',
    'hourly_advanced': 'hourly',
    'tax_advanced': 'tax',
    'investment_advanced': 'investment',
    'currency_advanced': 'currency',
    'pension_advanced': 'pension',
    'percent_advanced': 'percent',
    'sqrt_advanced': 'sqrt',
    'power_advanced': 'power',
    'fraction_advanced': 'fraction',
    'average_advanced': 'average',
    'log_advanced': 'log',
    'temperature_advanced': 'temperature',
    'fahrenheit_to_celsius_advanced': 'fahrenheit_to_celsius',
    'km_to_miles_advanced': 'km_to_miles',
    'miles_to_km_advanced': 'miles_to_km',
    'kg_to_lbs_advanced': 'kg_to_lbs',
    'lbs_to_kg_advanced': 'lbs_to_kg',
    'meter_to_feet_advanced': 'meter_to_feet',
    'cm_to_inches_advanced': 'cm_to_inches',
    'liter_to_gallon_advanced': 'liter_to_gallon',
    'ml_to_tsp_advanced': 'ml_to_tsp',
    'area_advanced': 'area',
    'circle_advanced': 'circle',
    'triangle_advanced': 'triangle',
    'pythagoras_advanced': 'pythagoras',
    'volume_advanced': 'volume',
    'sphere_advanced': 'sphere',
    'date_add_advanced': 'date_add',
    'time_diff_advanced': 'time_diff',
    'countdown_advanced': 'countdown',
    'speed_advanced': 'speed',
    'energy_advanced': 'energy',
    'force_advanced': 'force',
    'stddev_advanced': 'stddev',
    'median_advanced': 'median',
    'food_calories_advanced': 'food_calories',
    'concrete_advanced': 'concrete',
    'paint_advanced': 'paint',
    'child_bmi': 'bmi',
    'blood_sugar': 'bloodsugar',
    'cholesterol': 'generic',
    'nicotine': 'generic',
    'pregnancy_weight': 'generic',
    'breastfeeding': 'generic',
    'fever': 'generic',
    'medication_dosage': 'generic',
    'cycling': 'generic',
    'running': 'generic',
    'swimming': 'generic',
    'yoga': 'generic',
    'stress_test': 'generic',
    'sleep_quality': 'generic',
    'vitamins': 'generic',
    'minerals': 'generic',
    'allergy': 'generic',
    'vision': 'generic',
    'credit_card': 'loan',
    'dividend': 'investment',
    'net_worth': 'generic',
    'compound_interest': 'interest',
    'stocks': 'stock',
    'mutual_funds': 'investment',
    'real_estate': 'investment',
    'rental_income': 'roi',
    'business_budget': 'generic',
    'salary_growth': 'generic',
    'tips': 'tip',
    'invoice': 'generic',
    'currency_converter': 'currency',
    'prime_numbers': 'prime',
    'absolute_value': 'generic',
    'rounding': 'generic',
    'scientific_notation': 'generic',
    'hexadecimal': 'hex',
    'matrix': 'generic',
    'vector': 'generic',
    'complex_numbers': 'generic',
    'trigonometry': 'generic',
    'derivative': 'generic',
    'integral': 'generic',
    'statistics': 'stddev',
    'fibonacci': 'generic',
    'data_storage': 'bytes_to_mb',
    'area_conversion': 'acres_to_m2',
    'power_conversion': 'horsepower',
    'pressure_conversion': 'bar_to_psi',
    'speed_conversion': 'knots_to_kmh',
    'light_year': 'generic',
    'nanometer': 'generic',
    'troy_ounce': 'generic',
    'megawatt': 'generic',
    'tire_size': 'generic',
    'paper_size': 'generic',
    'color_conversion': 'generic',
    'energy_conversion': 'generic',
    'power_conversion_advanced': 'horsepower',
    'data_conversion': 'bytes_to_mb',
    'angle_conversion': 'deg_to_rad',
    'frequency_conversion': 'frequency',
    'density_conversion': 'density_calc',
    'cone': 'cone',
    'rhombus': 'generic',
    'parallelogram': 'generic',
    'regular_polygon': 'generic',
    'sector_area': 'generic',
    'arc_length': 'generic',
    'coordinates': 'generic',
    'work_days': 'working_days',
    'pension_countdown': 'retirement_countdown',
    'birthday_countdown': 'countdown',
    'timezone_converter': 'timezone_calc',
    'leap_year': 'generic',
    'week_number': 'generic',
    'semester': 'generic',
    'vacation': 'generic',
    'overtime': 'generic',
    'time_log': 'generic',
    'project_time': 'generic',
    'productivity': 'generic',
    'power_physics': 'watt_calc',
    'frequency_physics': 'frequency',
    'pressure_physics': 'pressure_calc',
    'temperature_physics': 'celsius_to_fahrenheit',
    'density_physics': 'density_calc',
    'buoyancy': 'generic',
    'magnetism': 'magnetic_force',
    'optics': 'snells_law',
    'nuclear_physics': 'half_life',
    'probability_distribution': 'probability',
    'z_score': 'zscore',
    'confidence_interval': 'generic',
    'regression': 'generic',
    'correlation': 'generic',
    'histogram': 'generic',
    'box_plot': 'generic',
    'protein_food': 'food_calories',
    'carbohydrate': 'food_calories',
    'fat_food': 'food_calories',
    'fiber_food': 'food_calories',
    'sugar_food': 'food_calories',
    'salt_food': 'food_calories',
    'water_food': 'food_calories',
    'alcohol_food': 'food_calories',
    'caffeine_food': 'food_calories',
    'glycemic_index': 'generic',
    'food_substitution': 'generic',
    'portion': 'recipe',
    'restaurant_price': 'unit_price',
    'food_budget': 'generic',
    'electrical': 'electricity',
    'plumbing': 'pipe_volume',
    'terrace': 'deck_calc',
    'garden': 'soil',
    'garage': 'concrete_calc',
    'attic': 'sqm_calculator',
}

fixed = 0
for tool in db['tools']:
    formula = tool.get('formula', '')
    if formula in fixes:
        tool['formula'] = fixes[formula]
        fixed += 1

with open('tools_database.json', 'w', encoding='utf-8') as f:
    json.dump(db, f, ensure_ascii=False, indent=2)

print(f'Fixed {fixed} formulas!')
